#!/bin/sh
set -e

# Railway injects the public port as $PORT; map it to Odoo's env-driven
# http_port setting (ODOO_HTTP_PORT is auto-generated by Odoo's config
# loader from the http_port option, same mechanism as PGHOST/PGUSER/etc).
export ODOO_HTTP_PORT="${ODOO_HTTP_PORT:-${PORT:-8069}}"

# Must match data_dir in docker/odoo.conf.
DATA_DIR=/var/lib/odoo/data
MIGRATION_DUMP=/opt/odoo/migration/roshaan.sql
MIGRATION_FILESTORE=/opt/odoo/migration/roshaan_filestore.tar.gz

if [ "$1" = "odoo" ] || [ "$1" = "odoo-bin" ]; then
    shift

    if [ -n "$PGDATABASE" ] && [ -n "$PGHOST" ]; then
        echo "entrypoint: checking whether database '$PGDATABASE' has an Odoo schema..."
        if ! PGPASSWORD="$PGPASSWORD" psql -h "$PGHOST" -p "${PGPORT:-5432}" -U "$PGUSER" -d "$PGDATABASE" -tAc \
                "SELECT 1 FROM information_schema.tables WHERE table_name = 'ir_module_module'" 2>/dev/null | grep -q 1; then

            if [ -f "$MIGRATION_DUMP" ]; then
                # Not using ON_ERROR_STOP: the dump may carry a newer source
                # server's session-level SET (e.g. transaction_timeout, PG17+)
                # that an older target server rejects. That's harmless noise;
                # psql skips the statement and keeps restoring. Real failures
                # are caught by the row-count/health checks done after deploy.
                echo "entrypoint: no schema found, restoring bundled migration dump into '$PGDATABASE'..."
                PGPASSWORD="$PGPASSWORD" psql -h "$PGHOST" -p "${PGPORT:-5432}" -U "$PGUSER" -d "$PGDATABASE" \
                    -f "$MIGRATION_DUMP"

                if [ -f "$MIGRATION_FILESTORE" ]; then
                    echo "entrypoint: restoring filestore into $DATA_DIR/filestore/$PGDATABASE ..."
                    mkdir -p "$DATA_DIR/filestore"
                    tar xzf "$MIGRATION_FILESTORE" -C "$DATA_DIR/filestore"
                    # the archive's top-level dir is the source db name (Roshaan);
                    # rename it to match this deploy's actual PGDATABASE.
                    src_dir=$(tar tzf "$MIGRATION_FILESTORE" | grep -v '^\._' | head -1 | cut -f1 -d/)
                    if [ "$src_dir" != "$PGDATABASE" ]; then
                        rm -rf "$DATA_DIR/filestore/$PGDATABASE"
                        mv "$DATA_DIR/filestore/$src_dir" "$DATA_DIR/filestore/$PGDATABASE"
                    fi
                fi
            else
                echo "entrypoint: no schema found, initializing 'base' module on '$PGDATABASE'..."
                python3 /opt/odoo/odoo-bin -c "$ODOO_RC" -i base --stop-after-init "$@"
            fi
        fi
    fi

    exec python3 /opt/odoo/odoo-bin -c "$ODOO_RC" "$@"
fi

exec "$@"
